[package]
name = "no-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.10.0"
rkyv = { version = "0.8", default-features = false }
rkyv_codec = { path = "../.." }
